### ISSUE TITLE
Installation probleme causes build failure

### ISSUE THREAD

**Issue by unmec** [eduedix/react-native-networking#6]
Thanks for this module.

When I try to integrate following the installation guide, I receive the following error in xcode when building the project:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-AFNetworking
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-AFNetworking is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods is not an object file (not allowed in a library)

I tried to add **_$(inherited)**_ to **_Other Linker Flags**_ of RNNetworkingManager but it still fails. Any help please? Thanks!

**Comment by eduedix** [comment]
are you sure you have installed the AFNetworking package?
please do:
`cd node_modules/react-native-networking && pod install`

**Comment by unmec** [comment]
Yes, I did pod install and all installation processes as explained in the readme.
I am using pod 0.39.

Google search suggests adding **_$(inherited)**_ to **_Other Linker Flags**_ but build still fails even I do so. :(

**Comment by eduedix** [comment]
I have reproduced this error, will try to fix it soon. I think this has something to do with cocoapods.

**Comment by unmec** [comment]
Agreed, I think cocoapods is the reason too.
Glad to hear! Many thanks in advance :)

**Comment by eduedix** [comment]
@macelii : it seems cocoapods is buggy these days: https://github.com/CocoaPods/CocoaPods/pull/3677 . I am not sure how to fix this problem though.

**Comment by eduedix** [comment]
@macelii : temporary solution: https://github.com/CocoaPods/CocoaPods/issues/4427#issuecomment-150389523

consider your project's name is `SomeTest` and follow the steps explained.

**Comment by eduedix** [comment]
https://github.com/eduedix/react-native-networking/blob/master/README.md has been updated accordingly.
