### ISSUE TITLE
Newer react-native version does not satisfy dependencies?

### ISSUE THREAD

**Issue by tijs** [eduedix/react-native-networking#7]
I get the following error when trying to install:

```
npm ERR! peerinvalid The package react-native@0.13.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-networking@0.0.9 wants react-native@^0.6.0
```

This might be an NPM issue since 0.13.2 seems to satisfy that dependency but could be the package.json needs to say `react-native@>=0.6.0` instead of `react-native@^0.6.0`?

**Comment by tijs** [comment]
if i change the dependency as noted above it does indeed install without issues.

from:

```
  "devDependencies": {
    "react-native": "^0.6.0"
  },
```

to:

```
  "devDependencies": {
    "react-native": ">=0.6.0"
  },
```

**Comment by eduedix** [comment]
Thanks for pointing out :).
