### ISSUE TITLE
why????

### ISSUE THREAD

**Issue by mvpdream** [eduedix/react-native-networking#9]
![image](https://cloud.githubusercontent.com/assets/16203724/14486894/1276c7d4-0192-11e6-905e-ed12e3817580.png)

**Comment by eduedix** [comment]
i have no idea what you are trying to do, so cannot help.

**Comment by mvpdream** [comment]
I just want to use this component to download method

**Comment by mvpdream** [comment]
grace Can use now why is returned error: 1000

**Comment by brianinator** [comment]
@mvpdream That is an error on the Android side. If you look at the function called downloadFile. DownloadManager is configured there to set visibility of download indicator.

Line that causes this:
`request.setNotificationVisibility(DownloadManager.Request.VISIBILITY_HIDDEN);`

**Comment by brianinator** [comment]
@eduedix Android implementation is extremely flawed. Is there plans to improve?

**Comment by thirteenthEyes** [comment]
You can try,
open'react-native-networking/android/src/main/java/com/learnium/RNNetworkingManager/RNNetworkingManagerModule.java',change  ' List<NativeModule> modules = new ArrayList <NativeModule> ();'.
Hope it helps.

**Comment by thirteenthEyes** [comment]
List<NativeModule> modules = new ArrayList <NativeModule> ();

**Comment by thirteenthEyes** [comment]
List    <NativeModule>    modules = new ArrayList    <NativeModule>     ();

**Comment by thirteenthEyes** [comment]
<NativeModule>    behind  List and Array

**Comment by thirteenthEyes** [comment]
List  |NativeModule|   modules = new ArrayList  |NativeModule|   ();
"|"  mean "<>"

**Comment by t880216t** [comment]
add this to AndroidManifest.xml
`<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />`
